name: SpecialEvents
version: '${project.version}'
main: me.dark_infect.specialevents.SpecialEvents
api-version: '1.21'
softdepend: [ ProtocolLib ]

commands:
  stev:
    usage: /stev
    permission: se.stev
  boss:
    usage: /boss
    permission: se.boss
  fishing:
    description: Fishing statistics and info
    usage: /fishing [stats|top|help]
  fishadmin:
    description: Open admin panel
    usage: /fishadmin
    aliases: [ fadmin, fishingadmin ]
    permission: fishing.admin
permissions:
  se.*:
    default: op
    children:
      se.stev: true
      se.immune: true
      se.debug: true
      se.boss: true
  fishing.use:
    description: Allows using the fishing system
    default: true
  fishing.admin:
    description: Access admin panel
    default: op